name: testing arc runner on minikube

on:
  workflow_call:
    inputs:
      region:
        description: 'Select the env'
        required: true
        type: string
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  echo:
    runs-on:
      group: Default
      labels: arc-runner-set
    steps:
      - name: Echo runner status
        run: |
          echo "runner working in region ${{ inputs.region }}"
          date
          sleep 30
